version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"

  migrator:
    build: .
    container_name: migrator-container
    environment:
      POSTGRES_PASSWORD: 12345
    command: ["./migrator", "--config=/root/config/local.yaml", "--migrations-path=/root/migrations"]
    depends_on:
      - db

  flat-seller:
    build: .
    container_name: flat-seller-container
    environment:
      POSTGRES_PASSWORD: 12345
      CONFIG_PATH: /root/config/local.yaml
    ports:
      - "8082:8082"
    depends_on:
      - migrator
