env: "local"
token_ttl: "10h"
secret: "afgjklfadgkjljfdbajklfadggj"
db:
    username: "postgres"
    host: "db"
    port: "5432"
    dbname: "postgres"
    sslmode: "disable"

http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 60s